- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/all.yml
  tasks:
    - name: Add-repository
      ansible.builtin.include_tasks: tasks/add-repository.yml
      when: ansible_os_family == "RedHat"

    - name: Install Alloy
      ansible.builtin.include_role:
        name: grafana.grafana.alloy
      vars:
        alloy_download_url_rpm: "{{ rpm_url }}"
        alloy_exposed_ports: true
        alloy_env_file_vars: 
          CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:12345"
        alloy_config: |
          prometheus.exporter.unix "host" {
            include_exporter_metrics = true
          }

          prometheus.scrape "host" {
            targets = prometheus.exporter.unix.host.targets
            forward_to = [prometheus.remote_write.mimir_host.receiver]
            scrape_interval = "15s"
          }

          prometheus.scrape "metamonitoring" {
            targets = 
              [{
                // Self-collect metrics
                job         = "alloy",
                __address__ = "127.0.0.1:12345",
              }]
            forward_to = [prometheus.remote_write.mimir_metamonitoring.receiver]
            scrape_interval = "15s"
          }

          prometheus.remote_write "mimir_host" {}

          prometheus.remote_write "mimir_metamonitoring" {}
          
          logging {
          level = "info"
          }
        